# Generated by Django 3.1.1 on 2020-12-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_auto_20201218_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
