# Generated by Django 3.1.1 on 2020-12-18 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_searchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchuser',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
